"use client"

import { Share2, FileText, FileSpreadsheet, FileJson, ImageIcon, Printer } from "lucide-react"
import { Button } from "@/components/ui/button"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"
import { toast } from "@/hooks/use-toast"
import type { ComparisonResult } from "@/types/comparison"
import type { Locale } from "@/lib/i18n"
import html2canvas from "html2canvas"

interface ExportShareMenuProps {
  results: ComparisonResult
  locale: Locale
}

export function ExportShareMenu({ results, locale }: ExportShareMenuProps) {
  const t =
    locale === "en"
      ? {
          exportShare: "Export & Share",
          exportAs: "Export as...",
          shareOn: "Share on...",
          markdown: "Markdown (.md)",
          csv: "CSV (.csv)",
          json: "JSON (.json)",
          image: "Image (.png)",
          print: "Print",
          twitter: "Twitter / X",
          linkedin: "LinkedIn",
          facebook: "Facebook",
          exportSuccess: "Export successful!",
          exportError: "Export failed",
          copied: "Link copied to clipboard!",
        }
      : {
          exportShare: "Exportar & Compartilhar",
          exportAs: "Exportar como...",
          shareOn: "Compartilhar em...",
          markdown: "Markdown (.md)",
          csv: "CSV (.csv)",
          json: "JSON (.json)",
          image: "Imagem (.png)",
          print: "Imprimir",
          twitter: "Twitter / X",
          linkedin: "LinkedIn",
          facebook: "Facebook",
          exportSuccess: "Exportação bem-sucedida!",
          exportError: "Falha na exportação",
          copied: "Link copiado para a área de transferência!",
        }

  const downloadFile = (content: string, filename: string, type: string) => {
    const blob = new Blob([content], { type })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = filename
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const exportAsMarkdown = () => {
    const md = `# QueueAdvisor - AWS Service Comparison

## Recommendation
**${results.recommendation}**

${results.explanation}

## Pricing Comparison (10M messages/month)
- **Amazon SQS**: ${results.pricing.sqs["10M"]}/month
- **Apache Kafka (MSK)**: ${results.pricing.kafka["10M"]}/month

## Metrics Comparison
${results.radarData.map((item) => `- **${item.metric}**: SQS ${item.sqs}/10, Kafka ${item.kafka}/10`).join("\n")}

---
Generated by QueueAdvisor - ${new Date().toLocaleDateString()}
`
    downloadFile(md, "queue-advisor-comparison.md", "text/markdown")
    toast({ title: t.exportSuccess, description: t.markdown })
  }

  const exportAsCSV = () => {
    const csv = `Metric,Amazon SQS,Apache Kafka (MSK)
${results.radarData.map((item) => `${item.metric},${item.sqs},${item.kafka}`).join("\n")}

Pricing (10M messages/month)
Monthly Cost,${results.pricing.sqs["10M"]},${results.pricing.kafka["10M"]}

Recommendation,${results.recommendation}
`
    downloadFile(csv, "queue-advisor-comparison.csv", "text/csv")
    toast({ title: t.exportSuccess, description: t.csv })
  }

  const exportAsJSON = () => {
    const json = JSON.stringify(results, null, 2)
    downloadFile(json, "queue-advisor-comparison.json", "application/json")
    toast({ title: t.exportSuccess, description: t.json })
  }

  const exportAsImage = async () => {
    try {
      const resultsElement = document.getElementById("results-container")
      if (!resultsElement) return

      const canvas = await html2canvas(resultsElement, {
        backgroundColor: null,
        scale: 2,
      })

      canvas.toBlob((blob) => {
        if (!blob) return
        const url = URL.createObjectURL(blob)
        const a = document.createElement("a")
        a.href = url
        a.download = "queue-advisor-comparison.png"
        document.body.appendChild(a)
        a.click()
        document.body.removeChild(a)
        URL.revokeObjectURL(url)
      })

      toast({ title: t.exportSuccess, description: t.image })
    } catch (error) {
      toast({ title: t.exportError, variant: "destructive" })
    }
  }

  const handlePrint = () => {
    window.print()
    toast({ title: t.exportSuccess, description: t.print })
  }

  const shareUrl = typeof window !== "undefined" ? window.location.href : ""
  const shareText = `Check out my AWS service comparison: ${results.recommendation} - Generated by QueueAdvisor`

  const shareOnTwitter = () => {
    const url = `https://twitter.com/intent/tweet?text=${encodeURIComponent(shareText)}&url=${encodeURIComponent(shareUrl)}`
    window.open(url, "_blank", "width=600,height=400")
  }

  const shareOnLinkedIn = () => {
    const url = `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(shareUrl)}`
    window.open(url, "_blank", "width=600,height=600")
  }

  const shareOnFacebook = () => {
    const url = `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(shareUrl)}`
    window.open(url, "_blank", "width=600,height=400")
  }

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="outline" className="gap-2 bg-transparent">
          <Share2 className="h-4 w-4" />
          {t.exportShare}
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" className="w-56">
        <DropdownMenuLabel>{t.exportAs}</DropdownMenuLabel>
        <DropdownMenuItem onClick={exportAsMarkdown} className="cursor-pointer">
          <FileText className="mr-2 h-4 w-4" />
          {t.markdown}
        </DropdownMenuItem>
        <DropdownMenuItem onClick={exportAsCSV} className="cursor-pointer">
          <FileSpreadsheet className="mr-2 h-4 w-4" />
          {t.csv}
        </DropdownMenuItem>
        <DropdownMenuItem onClick={exportAsJSON} className="cursor-pointer">
          <FileJson className="mr-2 h-4 w-4" />
          {t.json}
        </DropdownMenuItem>
        <DropdownMenuItem onClick={exportAsImage} className="cursor-pointer">
          <ImageIcon className="mr-2 h-4 w-4" />
          {t.image}
        </DropdownMenuItem>
        <DropdownMenuItem onClick={handlePrint} className="cursor-pointer">
          <Printer className="mr-2 h-4 w-4" />
          {t.print}
        </DropdownMenuItem>

        <DropdownMenuSeparator />

        <DropdownMenuLabel>{t.shareOn}</DropdownMenuLabel>
        <DropdownMenuItem onClick={shareOnTwitter} className="cursor-pointer">
          <svg className="mr-2 h-4 w-4" viewBox="0 0 24 24" fill="currentColor">
            <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z" />
          </svg>
          {t.twitter}
        </DropdownMenuItem>
        <DropdownMenuItem onClick={shareOnLinkedIn} className="cursor-pointer">
          <svg className="mr-2 h-4 w-4" viewBox="0 0 24 24" fill="currentColor">
            <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z" />
          </svg>
          {t.linkedin}
        </DropdownMenuItem>
        <DropdownMenuItem onClick={shareOnFacebook} className="cursor-pointer">
          <svg className="mr-2 h-4 w-4" viewBox="0 0 24 24" fill="currentColor">
            <path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z" />
          </svg>
          {t.facebook}
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  )
}
